import { useState } from 'react'
import { Circle, LayoutList, Columns3, Search } from 'lucide-react'
import type { TeamTask } from '../../core/teams/types'
export const taskStatusLabels: Record<TeamTask['status'], string> = { draft: '待执行', running: '执行中', paused: '已暂停', review: '待验收', done: '已完成', stopped: '已停止' }
export function TeamTaskCollection({ tasks, open }: { tasks: TeamTask[]; open: (id: string) => void }) {
  const [layout, setLayout] = useState<'list' | 'board'>('list')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('active')
  const [owner, setOwner] = useState('all')
  const [sort, setSort] = useState('updated')
  const ownerKey = (t: TeamTask) => `${t.target.kind}:${t.target.id}`
  const owners = [...new Map(tasks.map((t) => [ownerKey(t), t.team?.name ?? t.members[0]?.name ?? '未知成员'])).entries()]
  const shown = tasks.filter((t) => (status === 'all' || (status === 'active' ? !['done', 'stopped'].includes(t.status) : t.status === status)) && (owner === 'all' || ownerKey(t) === owner) && `${t.title} ${t.brief} ${t.team?.name ?? t.members[0]?.name}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'name' ? a.title.localeCompare(b.title) : sort === 'created' ? b.createdAt - a.createdAt : b.updatedAt - a.updatedAt)
  const columns = (Object.keys(taskStatusLabels) as TeamTask['status'][]).filter((s) => status === 'all' || (status === 'active' ? !['done', 'stopped'].includes(s) : s === status))
  return <div className="team-task-collection">
    <div className="team-collection-toolbar"><label className="team-mode-search"><Search size={14} /><input aria-label="搜索团队任务" placeholder="搜索任务" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select aria-label="任务状态筛选" value={status} onChange={(e) => setStatus(e.target.value)}><option value="active">未完成</option><option value="all">全部状态</option>{Object.entries(taskStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select aria-label="任务负责人筛选" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="all">全部负责人</option>{owners.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="任务排序" value={sort} onChange={(e) => setSort(e.target.value)}><option value="updated">最近更新</option><option value="created">最近创建</option><option value="name">名称</option></select><div className="team-layout-toggle"><button title="列表" aria-label="列表" aria-pressed={layout === 'list'} onClick={() => setLayout('list')}><LayoutList size={15} /></button><button title="看板" aria-label="看板" aria-pressed={layout === 'board'} onClick={() => setLayout('board')}><Columns3 size={15} /></button></div></div>
    {layout === 'list' ? <div className="team-mode-table" role="table" aria-label="团队任务"><div className="team-mode-table-head" role="row"><span role="columnheader">任务</span><span role="columnheader">负责人</span><span role="columnheader">状态</span><span role="columnheader">执行</span></div>{shown.map((t) => <div role="row" key={t.id} className="team-mode-task-row"><span role="cell"><button className="team-mode-task-title" onClick={() => open(t.id)}><Circle size={14} /><strong>{t.title}</strong></button></span><span role="cell" className="team-mode-owner">{t.team?.name ?? t.members[0]?.name}</span><span role="cell"><span className={`team-badge ${t.status}`}>{taskStatusLabels[t.status]}</span></span><span role="cell" className="team-mode-run-count">{t.steps.length}</span></div>)}</div> : <div className="team-board" aria-label="任务看板">{columns.map((status) => <section key={status} className="team-board-column" aria-label={taskStatusLabels[status]}><h3><span className={`team-status-dot ${status}`} />{taskStatusLabels[status]}<small>{shown.filter((t) => t.status === status).length}</small></h3>{shown.filter((t) => t.status === status).map((t) => <button className="team-board-card" key={t.id} onClick={() => open(t.id)}><strong>{t.title}</strong><span>{t.team?.name ?? t.members[0]?.name}</span><small>{t.steps.length} 次执行 · {new Date(t.updatedAt).toLocaleDateString()}</small></button>)}{!shown.some((t) => t.status === status) && <p>暂无任务</p>}</section>)}</div>}
    {!shown.length && layout === 'list' && <p className="team-empty">暂无匹配任务</p>}
  </div>
}
